name: flake8

on:
  pull_request:
    types: [opened, reopened, edited]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies with pip (flake8 and pygame)
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pygame
    - name: Analysing the code with flake8
      run: |
        flake8 --per-file-ignores="maze_levels.py:E501"
