name: python-analysis

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies with pip (flake8, pylint and pygame)
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint pygame
    - name: Analysing the code with pylint and flake8
      run: |
        pylint $(git ls-files '*.py') --enable=unused-import --max-line-length=79 --extension-pkg-whitelist=pygame --disable=protected-access,R,C
        flake8 --per-file-ignores="maze_levels.py:E501"
